<div class="mx-auto max-w-7xl space-y-6">
    <x-theme.section-header eyebrow="Komunikasi sekolah" title="Pengumuman & kalender" description="Sampaikan informasi ke seluruh sekolah atau kelas tertentu dan catat agenda akademik." />
    @if(session('communication_status'))<div class="rounded-2xl border border-tosca/25 bg-tosca-tint px-4 py-3 text-sm font-semibold text-navy">{{ session('communication_status') }}</div>@endif
    <div class="overflow-x-auto rounded-2xl border border-line bg-white p-1.5"><div class="flex min-w-max gap-1"><button wire:click="$set('tab','announcements')" @class(['rounded-xl px-5 py-2.5 text-sm font-semibold','bg-navy text-white'=>$tab==='announcements','text-ink-soft'=>$tab!=='announcements'])>Pengumuman</button><button wire:click="$set('tab','calendar')" @class(['rounded-xl px-5 py-2.5 text-sm font-semibold','bg-navy text-white'=>$tab==='calendar','text-ink-soft'=>$tab!=='calendar'])>Kalender akademik</button></div></div>
    @if($tab === 'announcements')
        <div class="grid gap-6 xl:grid-cols-[380px_minmax(0,1fr)]">
            <x-theme.card><h2 class="text-xl">Terbitkan pengumuman</h2><form wire:submit="saveAnnouncement" class="mt-5 space-y-4"><label class="block text-sm font-semibold text-navy">Judul<input wire:model="announcementTitle" class="mt-2 min-h-11 w-full rounded-xl border border-line px-3"></label>@error('announcementTitle')<p class="text-sm text-red-600">{{ $message }}</p>@enderror<label class="block text-sm font-semibold text-navy">Isi<textarea wire:model="announcementBody" rows="6" class="mt-2 w-full rounded-xl border border-line px-3 py-2"></textarea></label><label class="block text-sm font-semibold text-navy">Penerima<select wire:model.live="announcementTarget" class="mt-2 min-h-11 w-full rounded-xl border border-line px-3"><option value="all">Seluruh sekolah</option><option value="class">Kelas tertentu</option></select></label>@if($announcementTarget==='class')<label class="block text-sm font-semibold text-navy">Kelas<select wire:model="announcementClassId" class="mt-2 min-h-11 w-full rounded-xl border border-line px-3"><option value="">Pilih kelas</option>@foreach($classes as $class)<option value="{{ $class->id }}">{{ $class->name }}</option>@endforeach</select></label>@error('announcementClassId')<p class="text-sm text-red-600">{{ $message }}</p>@enderror@endif<x-theme.button type="submit" class="w-full" wire:loading.attr="disabled" wire:target="saveAnnouncement"><span wire:loading.remove wire:target="saveAnnouncement">Terbitkan</span><span wire:loading wire:target="saveAnnouncement">Menerbitkan...</span></x-theme.button></form></x-theme.card>
            <div class="space-y-4">@forelse($announcements as $announcement)<x-theme.card><div class="flex items-start gap-4"><span class="flex size-11 shrink-0 items-center justify-center rounded-xl bg-tosca-tint text-tosca"><flux:icon.megaphone class="size-5" /></span><div class="min-w-0 flex-1"><div class="flex flex-wrap items-start justify-between gap-2"><div><h3 class="text-lg">{{ $announcement->title }}</h3><p class="mt-1 text-sm text-ink-soft">{{ $announcement->creator->name }} · {{ $announcement->created_at?->format('d M Y, H:i') }}</p></div><x-theme.badge :tone="$announcement->target==='all'?'navy':'orange'">{{ $announcement->target==='all'?'Semua sekolah':$announcement->schoolClass?->name }}</x-theme.badge></div><p class="mt-4 whitespace-pre-line text-sm leading-6 text-ink">{{ $announcement->body }}</p><button wire:click="deleteAnnouncement({{ $announcement->id }})" wire:confirm="Hapus pengumuman ini?" class="mt-4 text-sm font-semibold text-red-600">Hapus</button></div></div></x-theme.card>@empty<x-theme.card class="py-14 text-center"><p class="text-sm text-ink-soft">Belum ada pengumuman.</p></x-theme.card>@endforelse</div>
        </div>
    @else
        <div class="grid gap-6 xl:grid-cols-[380px_minmax(0,1fr)]">
            <x-theme.card><h2 class="text-xl">Tambah agenda</h2><form wire:submit="saveEvent" class="mt-5 space-y-4"><label class="block text-sm font-semibold text-navy">Nama agenda<input wire:model="eventTitle" class="mt-2 min-h-11 w-full rounded-xl border border-line px-3"></label><label class="block text-sm font-semibold text-navy">Tanggal<input wire:model="eventDate" type="date" class="mt-2 min-h-11 w-full rounded-xl border border-line px-3"></label><label class="block text-sm font-semibold text-navy">Keterangan<textarea wire:model="eventDescription" rows="4" class="mt-2 w-full rounded-xl border border-line px-3 py-2"></textarea></label>@error('eventTitle')<p class="text-sm text-red-600">{{ $message }}</p>@enderror<x-theme.button type="submit" class="w-full" wire:loading.attr="disabled" wire:target="saveEvent"><span wire:loading.remove wire:target="saveEvent">Simpan agenda</span><span wire:loading wire:target="saveEvent">Menyimpan...</span></x-theme.button></form></x-theme.card>
            <x-theme.card :padding="false" class="overflow-hidden"><div class="border-b border-line px-5 py-5 sm:px-6"><h2 class="text-xl">Agenda akademik</h2></div><div class="divide-y divide-line">@forelse($events as $event)<div class="flex items-start gap-4 px-5 py-4 sm:px-6"><div class="w-14 shrink-0 rounded-xl bg-navy py-2 text-center text-white"><p class="text-lg font-semibold">{{ $event->date->format('d') }}</p><p class="text-xs uppercase">{{ $event->date->translatedFormat('M') }}</p></div><div class="min-w-0 flex-1"><p class="font-semibold text-navy">{{ $event->title }}</p><p class="mt-1 text-sm leading-6 text-ink-soft">{{ $event->description }}</p><p class="mt-1 text-xs text-ink-soft">Oleh {{ $event->creator->name }}</p></div><button wire:click="deleteEvent({{ $event->id }})" wire:confirm="Hapus agenda ini?" class="text-sm text-red-600">Hapus</button></div>@empty<div class="p-12 text-center text-sm text-ink-soft">Belum ada agenda.</div>@endforelse</div></x-theme.card>
        </div>
    @endif
</div>
