<x-layouts.siswa title="Dashboard Siswa">
    <div class="space-y-7">
        <section class="relative overflow-hidden rounded-card bg-gradient-to-br from-navy to-navy-mid px-5 py-7 text-white sm:px-8 sm:py-9">
            <div class="absolute -right-12 -top-16 size-48 rounded-full border-[28px] border-white/5"></div><div class="relative"><x-theme.badge tone="orange">{{ now()->translatedFormat('l, d F Y') }}</x-theme.badge><h1 class="mt-4 text-2xl text-white sm:text-3xl">Halo, {{ auth()->user()->name }}!</h1><p class="mt-2 text-sm text-white/70">Lihat jadwal, tugas, pengumuman, dan hasil belajar terbarumu.</p></div>
        </section>
        <section><div class="flex items-center justify-between"><h2 class="text-xl">Jadwal hari ini</h2><a href="{{ route('student.learning.index') }}" class="text-sm font-semibold text-tosca" wire:navigate>Ruang belajar</a></div><div class="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">@forelse($todaySchedules as $schedule)<x-theme.card class="border-t-4 border-t-tosca"><x-theme.badge tone="neutral">{{ substr($schedule->start_time,0,5) }}–{{ substr($schedule->end_time,0,5) }}</x-theme.badge><h3 class="mt-4 text-lg">{{ $schedule->classSubject->subject->name }}</h3><p class="mt-1 text-sm text-ink-soft">{{ $schedule->classSubject->teacher->name }}</p></x-theme.card>@empty<x-theme.card class="sm:col-span-2 lg:col-span-4 py-10 text-center"><p class="text-sm text-ink-soft">Tidak ada jadwal pelajaran hari ini.</p></x-theme.card>@endforelse</div></section>
        <div class="grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><x-theme.card :padding="false" class="overflow-hidden"><div class="flex items-center justify-between border-b border-line px-5 py-5 sm:px-6"><h2 class="text-xl">Tugas mendekati deadline</h2><x-theme.badge tone="orange">{{ $upcomingAssignments->count() }} aktif</x-theme.badge></div><div class="divide-y divide-line">@forelse($upcomingAssignments as $assignment)<article class="flex gap-4 px-5 py-4 sm:px-6"><span class="flex size-11 shrink-0 items-center justify-center rounded-xl bg-orange/15 text-orange"><flux:icon.clipboard-document-check class="size-5" /></span><div class="min-w-0 flex-1"><div class="flex flex-wrap justify-between gap-2"><h3 class="font-semibold text-navy">{{ $assignment->title }}</h3><x-theme.badge tone="orange">{{ $assignment->deadline->diffForHumans() }}</x-theme.badge></div><p class="mt-1 text-sm text-ink-soft">{{ $assignment->classSubject->subject->name }} · {{ $assignment->classSubject->teacher->name }}</p></div></article>@empty<div class="p-10 text-center text-sm text-ink-soft">Tidak ada tugas yang jatuh tempo minggu ini.</div>@endforelse</div></x-theme.card>
            <x-theme.card><div class="flex items-center justify-between"><h2 class="text-xl">Nilai terbaru</h2><a href="{{ route('student.evaluation.index') }}" class="text-sm font-semibold text-tosca" wire:navigate>Lihat semua</a></div><div class="mt-5 space-y-3">@forelse($recentGrades as $grade)<div class="flex items-center justify-between rounded-xl bg-offwhite p-3"><div><p class="text-sm font-semibold text-navy">{{ $grade->classSubject->subject->name }}</p><p class="text-xs text-ink-soft">Predikat {{ $grade->predikat }}</p></div><span class="text-xl font-semibold text-tosca">{{ number_format((float)$grade->final_score,0) }}</span></div>@empty<p class="text-sm text-ink-soft">Belum ada nilai akhir.</p>@endforelse</div></x-theme.card></div>
        <div class="grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><x-theme.card :padding="false" class="overflow-hidden"><div class="border-b border-line px-5 py-5 sm:px-6"><h2 class="text-xl">Pengumuman terbaru</h2></div><div class="divide-y divide-line">@forelse($announcements as $item)<article class="px-5 py-4 sm:px-6"><div class="flex flex-wrap justify-between gap-2"><h3 class="font-semibold text-navy">{{ $item->title }}</h3><x-theme.badge :tone="$item->target==='all'?'navy':'orange'">{{ $item->target==='all'?'Sekolah':$item->schoolClass?->name }}</x-theme.badge></div><p class="mt-2 whitespace-pre-line text-sm leading-6 text-ink-soft">{{ $item->body }}</p><p class="mt-2 text-xs text-ink-soft">{{ $item->creator->name }} · {{ $item->created_at?->diffForHumans() }}</p></article>@empty<div class="p-10 text-center text-sm text-ink-soft">Belum ada pengumuman.</div>@endforelse</div></x-theme.card><x-theme.card><h2 class="text-xl">Agenda akademik</h2><div class="mt-5 space-y-4">@forelse($events as $event)<div class="flex gap-3"><span class="flex size-11 shrink-0 flex-col items-center justify-center rounded-xl bg-tosca-tint text-navy"><strong>{{ $event->date->format('d') }}</strong><small>{{ $event->date->translatedFormat('M') }}</small></span><div><p class="text-sm font-semibold text-navy">{{ $event->title }}</p><p class="mt-0.5 text-xs leading-5 text-ink-soft">{{ $event->description }}</p></div></div>@empty<p class="text-sm text-ink-soft">Belum ada agenda mendatang.</p>@endforelse</div></x-theme.card></div>
    </div>
</x-layouts.siswa>
